config/routes.rb
Rails.application.routes.draw do
  root 				 'stories#index'
  get 	 'signup' => 'members#new'
  get 	 'login'  => 'session#new'
  post   'login'  => 'session#create'
  delete 'logout' => 'session#destroy'
  resources :stories
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :stories
  before_save { self.email = email.downcase }
  before_validation :remember, on: :create
  validates :name, presence: true, length: { minimum: 4, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
					format:   { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  # Returns the hash digest of the given string
  def Member.digest(string)
	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
												  BCrypt::Engine.cost
	BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def Member.new_token
	SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
	self.remember_token = Member.new_token
	update_attribute(:remember_digest, Member.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
	return false if remember_digest.nil?
	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
	update_attribute(:remember_digest, nil)
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :member
  validates :body, presence: true, length: { minimum: 10, maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
	member = Member.find_by(email: params[:session][:email].downcase)
	if member && member.authenticate(params[:session][:password])
	  # Log's the user in and remembers him/her by default
	  log_in member
	  flash.now[:success] = "Welcome to Members only!"
	  redirect_to root_url
	else
	  flash.now[:danger] = "Invalid email/password combination!"
	  render :new
	end
  end

  def destroy
	log_out if logged_in?
	redirect_to root_url
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :logged_member, only: [:new, :create]

  def new
	@story = Story.new
  end

  def create
	@story = Story.new(body: params[:story][:body], member_id: current_member.id)
	if @story.save
	  flash.now[:success] = "Story posted successfully"
	  redirect_to root_url
	else
	  render :new
	end
  end

  def index
	@stories = Story.paginate(page: params[:page]).order(created_at: :desc)
  end

  private
	def logged_member
	  unless logged_in?
		flash.now[:info] = "Please log in"
		redirect_to login_path
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Members only"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper

  # Log's the given member in
  def log_in(member)
	current_member=(member)
	session[:member_id] = member.id
	remember(member)
  end

  # Set's cookies to remember current member
  def remember(member)
	member.remember
	cookies.permanent.signed[:member_id] = member.id
	cookies.permanent[:remember_token] 	 = member.remember_token
  end

  # Returns the currently logged in member
  def current_member
	if (member_id = session[:member_id])
	  current_member=(Member.find_by(id: member_id))
	elsif (member_id = cookies.signed[:member_id])
	  member = Member.find_by(id: member_id)
	  if member && member.authenticated?(cookies[:remember_token])
	    log_in member
		current_member=(member)
	  end
	end
  end

  # Set's the current member if it's not set already
  def current_member=(member)
	@current_member ||= member
  end

  # Checks if a member is logged in
  def logged_in?
	!current_member.nil?
  end

  def forget(member)
	member.forget
	cookies.delete(:member_id)
	cookies.delete(:remember_token)
  end

  # Log's out the given member
  def log_out
	forget(current_member)
	session.delete(:member_id)
	current_member=(nil)
  end

end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Matias Pan - <a href="https://github.com/kriox26">Github</a> - 
    Watch the <a href="https://github.com/kriox26/members-only">source code</a>
  </small>
  <nav>
    <ul>
	  <a href="http://www.theodinproject.com">TOP</a>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MEMBERS ONLY", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Stories", root_url %></li>
		<% if !logged_in? %>
		  <li><%= link_to "Log in", login_url %></li>
		<% else %>
		  <li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Member<b class="carret"></b></a>
			<ul class="dropdown-menu">
			  <li><%= link_to "Create story", new_story_path %></li>
			  <li class="divider"></li>
			  <li><%= link_to "Log out", logout_path, method: :delete %></li>
			</ul>
		  </li>
		<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title> <%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag 'application', media: 'all',
	  'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>

	<div class="container">
	  <% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	  <% end %>
	  <%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/session/new.html.erb
<%= provide :title, "Login" %>
<h1 class="text-info">Login</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f|  %>

	  <%= f.label :email %>
	  <%= f.email_field :email, class: 'form-control' %>

	  <%= f.label :password %>
	  <%= f.password_field :password, class: 'form-control' %>

	  <%= f.submit "Log in", class: 'btn btn-primary' %>
	<% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if @story.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@story.errors.count, 'error') %>.
    </div>
	<ul>
	  <% @story.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	  <% end %>
	</ul>
  </div>
<% end %>

app/views/stories/_story.html.erb
<div class="panel panel-default my-box">
  <li>
	<div class="panel panel-info">
	  <div class="panel-heading">
		<span class="glyphicon glyphicon-time"></span> Story created <%= distance_of_time_in_words(Time.now, story.created_at) %> ago
	  </div>
	  <div class="panel-body">
		<p class="story-body"><%= story.body %></p>
	  </div>
	  <div class="panel-footer">
		<p class="text-muted">
		  <% if logged_in? %>
			<p class="text-muted member-name">
			  <span class="glyphicon glyphicon-star"></span> Author: <%= Member.find(story.member_id).name %>
		  </p>
		<% else %>
		  <p class="text-danger"><small>You need to be logged in to view the author of this story</small></p>
		<% end %>
	  </p>
	</div>
  </div>
</li>
</div>

app/views/stories/create.html.erb
<h1>Story#create</h1>
<p>Find me in app/views/story/create.html.erb</p>

app/views/stories/index.html.erb
<h2 class="text-info">All stories</h2>
<div class="col-md-6 col-md-offset-3">
  <%= will_paginate %>
  <ul class="stories">
	<%= render @stories %>
  </ul>
</div>

app/views/stories/new.html.erb
<h1 class="text-info">Creating a Story</h1>
<br />
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= render 'shared/errors' %>
	<%= form_for @story do |f| %>

	  <%= f.label :body %>
	  <%= f.text_area :body, class: 'form-control' %>

	  <%= f.submit "Create story", class: 'btn btn-info' %>
	<% end %>
  </div>
</div>